# Generated by Django 4.2.5 on 2023-09-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_worker_position_alter_worker_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('is_done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_points', to='task.task')),
            ],
        ),
    ]
