# Generated by Django 4.2.5 on 2023-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m/%d'),
        ),
    ]
